

function calc_areas(plane)

   plane.wing.area = plane.wing.chord_root*...
                     (1 + plane.wing.taper_ratio)*...
                     plane.wing.span/2.0;         % wing area  

   plane.wing.wetted_area = plane.wing.area - plane.fuselage.width*plane.wing.chord_root; 
   
   plane.wing.aspect_ratio = plane.wing.span^2/plane.wing.area;
   
   plane.horz_stabiliser.area = plane.horz_stabiliser.span*...
                                plane.horz_stabiliser.chord_root;                              %area of horizontal stabilizer                     [m^2].
   plane.vert_stabiliser.area = plane.horz_stabiliser.area*...
                                tand(plane.vert_stabiliser.angle);                %area of vertical stabilizer   



    plane.landing_gear.area = 2*((sqrt(plane.fuselage.height/...
        2-plane.landing_gear.wheel_height)^2+(plane.wing.span/...
        3-plane.landing_gear.wheel_width/2)^2)*plane.landing_gear.strut_thickness1+...
        (plane.landing_gear.wheel_width*plane.landing_gear.wheel_height))+...
        ((plane.fuselage.height/2-plane.landing_gear.wheel_height)*...
        plane.landing_gear.strut_thickness2+...
        (plane.landing_gear.wheel_width*plane.landing_gear.wheel_height));

end