%Name:    Isaac Nakone
%Date:    11/12/2023
%Purpose: This is a function which takes in an 
%         aircraft and outputs the clearance
%         in the battery capacity.

%Description from constraint set:
%   Battery Capacity versus cruise required (BC).


function BC = con_BC( plane)
    %For mission 2 we need to fly 3 laps
    plane.battery.required_capacity2 = plane.cruise_properties.power2*...
        (3*plane.cruise_properties.time2/60)*...
        1.25*plane.units.W2mW*plane.units.min2h/...
        plane.battery.voltage - plane.motor.power_max*...                   %Assuming that you initially fly at max power for 20 seconds
        20/60*...
        1.25*plane.units.W2mW*plane.units.min2h/...
        plane.battery.voltage;

    plane.battery.required_capacity3 = plane.cruise_properties.power3*...
        (5 + plane.misc_properties.time_safety)*...
        1.25*plane.units.W2mW*plane.units.min2h/...
        plane.battery.voltage - plane.motor.power_max*...                   %Assuming that you initially fly at max power for 20 seconds
        20/60*...
        1.25*plane.units.W2mW*plane.units.min2h/...
        plane.battery.voltage;
    
    BC =[ plane.battery.capacity -...
        plane.battery.required_capacity2;
        plane.battery.capacity - plane.battery.required_capacity3]; %This will be in mAh. (or is it mWh)
end