
function calc_empty_mass(plane)

    
                                                 
    plane.fuselage.mass = (2*plane.fuselage.length*plane.fuselage.height+...
                           2*plane.fuselage.length*plane.fuselage.width+...
                           plane.nose.length*plane.fuselage.width+...
                           0.5*2*plane.nose.length*plane.fuselage.width+...
                           plane.fuselage.width*sqrt(...
                           plane.nose.length^2+plane.fuselage.height^2)+...
                           2*plane.fuselage.tail_length*...
                           plane.fuselage.width +...
                           plane.fuselage.width*sqrt(...
                           plane.fuselage.tail_length^2 +...
                           plane.fuselage.height^2) )*...
                           plane.fuselage.wall_thickness*...
                           plane.fuselage.density;
    
    plane.wing.mass = plane.wing.area*plane.wing.layer_thickness*plane.wing.area_density;
    
    
    % for conventional tai;
    plane.vert_stabiliser.mass = plane.vert_stabiliser.area*...
        plane.vert_stabiliser.area_density;
    plane.horz_stabiliser.mass = 2*plane.horz_stabiliser.area*...
        plane.horz_stabiliser.area_density;
    
    %use pythogas to fix
    
    
    plane.fuselage.empty_mass = 1.25*(plane.fuselage.mass+plane.wing.mass+...
        plane.wing.mass+plane.vert_stabiliser.mass+...
        plane.horz_stabiliser.mass)+(plane.servos.mass*plane.servos.number+...
        plane.motor.number*plane.motor.mass+plane.landing_gear.mass+...
        plane.electronics.mass)+plane.battery.mass;

    plane.trays.mass = ((plane.cabin.length*plane.fuselage.width)*...
                        plane.trays.thickness+...
                        (plane.fuselage.width*...
                        (plane.medical_bay.length+...
                        plane.msc.length))*plane.trays.thickness)*...
                        plane.misc_properties.density_PETG;
  

end