

function [CD_CR_2, CD_CR_3] = C_D_AtCruise(V_CR_2, V_CR_3, plane)

    [C_L_CR_2, C_L_CR_3] = C_LAtCruise(V_CR_2,V_CR_3 ,plane);

    C_L_CR_2_HS = 2*plane.mass2*plane.physics.gravity/...
             plane.physics.air_density30/V_CR_2^2/plane.horz_stabiliser.area;
    C_L_CR_3_HS = 2*plane.mass3*plane.physics.gravity/...
             plane.physics.air_density30/V_CR_3^2/plane.horz_stabiliser.area;
    C_L_CR_2_VS = 2*plane.mass2*plane.physics.gravity/...
             plane.physics.air_density30/V_CR_2^2/plane.vert_stabiliser.area;
    C_L_CR_3_VS = 2*plane.mass3*plane.physics.gravity/...
             plane.physics.air_density30/V_CR_3^2/plane.vert_stabiliser.area;


    CD_CR_2 = get_CD(plane.wing.coeff_drag_data,...
                    plane.wing.coeff_lift0,...
                    plane.wing.coeff_liftA,C_L_CR_2);

    CD_CR_3 = get_CD(plane.wing.coeff_drag_data,...
                    plane.wing.coeff_lift0,...
                    plane.wing.coeff_liftA,C_L_CR_3);

    plane.horz_stabiliser.coeff_drag2 = get_CD(plane.horz_stabiliser.coeff_drag_data,...
                    plane.horz_stabiliser.coeff_lift0,...
                    plane.horz_stabiliser.coeff_liftA,C_L_CR_2_HS);
    plane.horz_stabiliser.coeff_drag3 = get_CD(plane.horz_stabiliser.coeff_drag_data,...
                    plane.horz_stabiliser.coeff_lift0,...
                    plane.horz_stabiliser.coeff_liftA,C_L_CR_3_HS);
    
    plane.vert_stabiliser.coeff_drag2 = get_CD(plane.horz_stabiliser.coeff_drag_data,...
                    plane.horz_stabiliser.coeff_lift0,...
                    plane.horz_stabiliser.coeff_liftA,C_L_CR_2_VS);

    plane.vert_stabiliser.coeff_drag3 = get_CD(plane.horz_stabiliser.coeff_drag_data,...
                    plane.horz_stabiliser.coeff_lift0,...
                    plane.horz_stabiliser.coeff_liftA,C_L_CR_3_VS);




end