


function calc_COG3(plane)

    plane.fuselage.COG = 0.5*plane.fuselage.length;

    plane.cabin.COG   = plane.nose.length + 0.5*plane.cabin.length; 
    plane.trays.COG   = 0.5*plane.fuselage.length;
    plane.wing.COG    = plane.wing.position + 0.5*plane.wing.chord_root;                                                      %Center of gravity of wings
    plane.motor.COG   = plane.wing.position;                                                                %Center of gravity of the motor (assumed to be at the tip of the wing)
    plane.battery.COG = plane.nose.length + 0.5*plane.battery.length;                                          %Assume that the battery is as close ot the front of the plane as that gives the msot stable design.
    plane.horz_stabiliser.COG = plane.wing.span/plane.misc_properties.aspect_ratio...
                                - 0.5*plane.horz_stabiliser.chord_root;                                                        %Center of Gravity of Tail
    %Landing Gear - assumed to be in the center of the fuelage for the
    %purpose of CG calcs
    plane.landing_gear.COG = 0.5*plane.fuselage.length;

    %Mission 2 Specific Calculations
    plane.passengers.COG = plane.nose.length+plane.passengers.length+plane.cabin.length+...
                           plane.fuselage.wall_thickness;
        

    %C_G for mission 3 (make sure we check over these as there may be some
    %incorrect formulae).
    plane.COG3 =plane.fuselage.COG*plane.fuselage.mass+...
                plane.battery.COG*plane.battery.mass+...
                plane.cabin.COG*(2*plane.crew.mass)+...
                plane.passengers.COG*(plane.passengers.doll_mass*...
                plane.passengers.total)+...
                plane.trays.COG*plane.trays.mass+...
                plane.wing.COG*plane.wing.mass+...
                plane.horz_stabiliser.COG*...
                (plane.horz_stabiliser.mass+...
                plane.vert_stabiliser.mass)+...
                plane.landing_gear.COG*plane.landing_gear.mass+...
                plane.motor.COG*(plane.motor.number*...
                plane.motor.mass)+...
                plane.wing.COG*(8*plane.servos.mass);

    plane.COG3 = plane.COG3/plane.mass3;
end