%Name:        Isaac Nakone, Denis Vasilyev, Harry Rowton, Jingya Liu 
%Date:        10/12/2023
%Description: This finds the oswald efficiency for a given V_CR.
%Inputs:
%       (1) V_CR  == the cruise velocity.


function [e2,e3] = oswald_efficiency(V_CR_2,V_CR_3, plane)

    plane.wing.MAC = (2/3)*(plane.wing.chord_root)*...
        ((1+plane.wing.taper_ratio+plane.wing.taper_ratio^2)/...
        (1+plane.wing.taper_ratio));




    tOnC2 =  plane.wing.thickness; %Multiplying by C_w_r to normalise the interval.
    %Get Harry to check this!!!

    tOnC3 =  plane.wing.thickness; %Multiplying by C_w_r to normalise the interval.

    e2 = (1+0.12*(V_CR_2/sqrt(...
        plane.physics.thermodynamic_ratio*...
        plane.physics.gas_constant*...
        plane.physics.temperature))^6)^(-1) * ...
        ( 1.0 +(0.142+0.005*(1.0+1.5*...
        (plane.wing.taper_ratio-0.6)^2)*...
        plane.wing.aspect_ratio*(10*tOnC2)^0.33)/...
        cosd(plane.wing.sweep_angle25)^2 + ...
        0.1*(3*plane.motor.number+1)/...
        (4+plane.wing.aspect_ratio)^0.8)^(-1);

    e3 = (1+0.12*(V_CR_3/sqrt(...
        plane.physics.thermodynamic_ratio*...
        plane.physics.gas_constant*...
        plane.physics.temperature))^6)^(-1) * ...
        ( 1.0 +(0.142+0.005*(1.0+1.5*...
        (plane.wing.taper_ratio-0.6)^2)*...
        plane.wing.aspect_ratio*(10*tOnC3)^0.33)/...
        cosd(plane.wing.sweep_angle25)^2 + ...
        0.1*(3*plane.motor.number+1)/...
        (4+plane.wing.aspect_ratio)^0.8)^(-1);

end